mode: prod
prod:
  - botname: VingPN Reseller
    username: VingPNResellerBot
    admin: 1211590718
    subscription-domain: "sub.vingpn.me"
    token: 
      5905904928:AAH4IiRwmj8u6BEQO37-U1mKmw2TbBLud3A
    about:
      "this is some short text about my bot"
    description:
      "This is a description of what my bot can do which customer will use"
    database:
      "mongodb+srv://erf743120:test@cluster0.mcrthsr.mongodb.net/?retryWrites=true&w=majority"